export const COLLECTIONS = {
  USERS: "users",
  ROLES: "roles",
  MACHINES: "machines",
  PARTS: "parts",
  PARTS_MASTER: "parts_master",
  JOBS: "jobs",
  LOGS: "logs",
  ATTENDANCE: "attendance",
  SALARIES: "salaries",
  SALARY_RECORDS_V2: "salaryRecords",
  SALARY_CONFIGS: "salaryConfigs",
  SALARY_SETTLEMENTS: "salarySettlements",
  SALARY_RECORDS: "salary_records",
  REPORTS: "reports",
  OPERATOR_MONTHLY_STATS: "operatorMonthlyStats",
  OPERATOR_YEARLY_STATS: "operatorYearlyStats",
  MACHINE_MONTHLY_STATS: "machineMonthlyStats",
  MACHINE_YEARLY_STATS: "machineYearlyStats",
  SETTINGS: "settings",
  AUDIT_LOGS: "auditLogs"
};
