import * as FileSystem from "expo-file-system";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { aggregateReports } from "./calculations";
import { formatDateTime, formatPercent } from "./formatters";

const escapeHtml = (value) =>
  String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

export const exportReportsPdf = async ({ title = "Efficiency Calculator Report", subtitle = "", reports = [] } = {}) => {
  const summary = aggregateReports(reports);
  const generatedAt = new Date();
  const rows = reports
    .map(
      (item) => `
        <tr>
          <td>${escapeHtml(formatDateTime(item.timestamp))}</td>
          <td>${escapeHtml(item.machineName || "-")}</td>
          <td>${escapeHtml(item.workerName || item.operatorName || "-")}</td>
          <td>${escapeHtml(item.runtimeMinutes ?? "-")}</td>
          <td>${escapeHtml(item.outputProduced ?? item.actualProduction ?? 0)}</td>
          <td>${escapeHtml(item.expectedProduction ?? item.expectedOutput ?? 0)}</td>
          <td>${escapeHtml(formatPercent(item.efficiency))}</td>
        </tr>`
    )
    .join("");

  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>
          body { font-family: Arial, sans-serif; color: #111827; padding: 24px; }
          h1 { font-size: 24px; margin: 0 0 4px; }
          h2 { font-size: 14px; color: #4B5563; margin: 0 0 20px; font-weight: 400; }
          .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-bottom: 20px; }
          .metric { border: 1px solid #E5E7EB; border-radius: 8px; padding: 10px; }
          .label { color: #6B7280; font-size: 11px; text-transform: uppercase; }
          .value { font-size: 18px; font-weight: 700; margin-top: 4px; }
          table { width: 100%; border-collapse: collapse; font-size: 11px; }
          th, td { border-bottom: 1px solid #E5E7EB; padding: 8px; text-align: left; }
          th { background: #F3F4F6; }
          footer { margin-top: 18px; color: #6B7280; font-size: 11px; }
        </style>
      </head>
      <body>
        <h1>${escapeHtml(title)}</h1>
        <h2>${escapeHtml(subtitle)}</h2>
        <div class="grid">
          <div class="metric"><div class="label">Jobs</div><div class="value">${summary.totalJobs}</div></div>
          <div class="metric"><div class="label">Runtime</div><div class="value">${summary.runtimeMinutes.toFixed(0)} min</div></div>
          <div class="metric"><div class="label">Production</div><div class="value">${summary.production.toFixed(0)}</div></div>
          <div class="metric"><div class="label">Efficiency</div><div class="value">${formatPercent(summary.efficiency)}</div></div>
        </div>
        <table>
          <thead><tr><th>Date</th><th>Machine</th><th>Operator</th><th>Runtime</th><th>Actual</th><th>Expected</th><th>Efficiency</th></tr></thead>
          <tbody>${rows || "<tr><td colspan='7'>No reports available.</td></tr>"}</tbody>
        </table>
        <footer>Generated by Efficiency Calculator at ${escapeHtml(formatDateTime(generatedAt))}</footer>
      </body>
    </html>`;

  const file = await Print.printToFileAsync({ html });
  const targetUri = `${FileSystem.cacheDirectory || ""}${title.replace(/[^a-z0-9]+/gi, "_").toLowerCase()}_${Date.now()}.pdf`;
  await FileSystem.copyAsync({ from: file.uri, to: targetUri });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(targetUri, { mimeType: "application/pdf", dialogTitle: title });
  }
  return targetUri;
};

export const exportTablePdf = async ({ title = "Efficiency Calculator Export", subtitle = "", columns = [], rows = [] } = {}) => {
  const generatedAt = new Date();
  const header = columns.map((column) => `<th>${escapeHtml(column.label)}</th>`).join("");
  const body = rows
    .map(
      (row) => `
        <tr>
          ${columns.map((column) => `<td>${escapeHtml(row[column.key] ?? "")}</td>`).join("")}
        </tr>`
    )
    .join("");

  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>
          body { font-family: Arial, sans-serif; color: #111827; padding: 24px; }
          h1 { font-size: 24px; margin: 0 0 4px; }
          h2 { font-size: 14px; color: #4B5563; margin: 0 0 18px; font-weight: 400; }
          table { width: 100%; border-collapse: collapse; font-size: 11px; }
          th, td { border: 1px solid #E5E7EB; padding: 8px; text-align: left; vertical-align: top; }
          th { background: #F3F4F6; font-weight: 700; }
          tr:nth-child(even) td { background: #F9FAFB; }
          footer { margin-top: 18px; color: #6B7280; font-size: 11px; }
        </style>
      </head>
      <body>
        <h1>${escapeHtml(title)}</h1>
        <h2>${escapeHtml(subtitle)}</h2>
        <table>
          <thead><tr>${header}</tr></thead>
          <tbody>${body || `<tr><td colspan="${columns.length || 1}">No records available.</td></tr>`}</tbody>
        </table>
        <footer>Generated by Efficiency Calculator at ${escapeHtml(formatDateTime(generatedAt))}</footer>
      </body>
    </html>`;

  const file = await Print.printToFileAsync({ html });
  const targetUri = `${FileSystem.cacheDirectory || ""}${title.replace(/[^a-z0-9]+/gi, "_").toLowerCase()}_${Date.now()}.pdf`;
  await FileSystem.copyAsync({ from: file.uri, to: targetUri });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(targetUri, { mimeType: "application/pdf", dialogTitle: title });
  }
  return targetUri;
};
